### PR TITLE
flagship vmod

### PR DESCRIPTION
**Pull request by Chadiii**

### CODE REVIEW

**Comment by nigoroll** [comment]
@Chadiii it is, thank you.
I am a bit skeptical about labeling this vmod as licensed under the Apache License 2.0. Yes, you have used that in the repo, but the vmod code really only wraps calls to your library, of which you seem to bundle a binary shared object. As such I would not consider the vmod open source?

**Comment by Chadiii** [comment]
Hi, thanks for the feedback.
we released the library that generate the binary shared object [link](https://github.com/flagship-io/flagship-c-go-wrapper), and its under Apache2 License.

**Comment by nigoroll** [comment]
@Chadiii Thank you. So do I understand correctly that your project is open source back to front and can be built independently?

Other than that, I would still recommend against bundling binary shared objects. Why not add a link to install and/or build instructions?

**Comment by Chadiii** [comment]
@nigoroll Indeed, the project is mostly back and its open source under Apache License.

For the shared object part, since the lib is used also by our custom nginx module, we choose to separate the lib and put instructions on how to build the binary [link](https://github.com/flagship-io/libvmod-flagship#shared-object). The run [section](https://github.com/flagship-io/flagship-c-go-wrapper#run) is indeed the installation part (the shell script generate the binary).
we also got some examples in other repos that we dockerized and it was simple for us to include the binary directly and not adding the step to build it.

**Pull request merged**
