### PR TITLE
Add a few of the VMOD pages back

### PR DESCRIPTION
**Pull request by glennslaven**
Small PR to add a few of the VMOD pages back in.  This is just the content that was on those pages before.

### CODE REVIEW

**Comment by bsdphk** [comment]
Thanks for the patches!

I don't think maintaining the VMOD pages as raw RST is a viable long term strategy.

How about we put the info for each VMOD in a small json file, and generate the table/pages based on that when we build the homepages ?

That way adding or deleting a VMOD is just a single file operation, and the data can be reused in other ways too, as appendix in a book or for automated buildtests/continuous integration.

Input, comments ?

**Comment by bsdphk** [comment]
Talking to myself here:  I've decided that the JSON thing is the way to go.  I'll write some scripts...

**Comment by glennslaven** [comment]
That sounds like a better option to me

**Comment by bsdphk** [comment]
I've done most of the footwork to build this from JSON (check the page now)

Ideally I would like the version numbers (3.0/4.1 etc.) to point to the formatted *.vcc file, as a way to encourage people to fill in the documentation.

I would also like to add a contact person to send email if automatic builds find problems.

And finally it would be nice if we could run build-tests on at least one Linux distro and FreeBSD and mark which VMODs work on what OS.

But at least now we don't have to edit that huge table by hand.

**Comment by bsdphk** [comment]
so... now it looks like something we can work from.

Ideally we should convert the VCC files to RST (rev 4+) but that is left as an exercise to feels like it.

(Volunteers very welcome!)

Thanks for prodding me into getting this done.

**Pull request closed without merging**
