### PR TITLE
List the vmod_remoteip module

### PR DESCRIPTION
**Pull request by graygnuorg**
This adds information about new vmod_remoteip to the vmods page.

### CODE REVIEW

**Comment by Dridi** [comment]
Can you please update your pull request to get rid of the merge commit?

**Comment by Dridi** [comment]
By the way, why don't you take an ACL instead of a STRING in `remoteip.init()`? That would save you a lot of code and come with compile-time guarantees.

**Comment by graygnuorg** [comment]
Dridi Boukelmoune <notifications@github.com> ha escrit:

> By the way, why don't you take an ACL instead of a STRING in
> `remoteip.init()`?

That was my initial idea, as a matter of fact.  However, I was stopped
by the fact the only function API provides for creating a VCL_IP -
VSS_ResolveFirst - is not prototyped in headers that are made public
after installation.  Its prototype is in vss.h, which is not installed.

Anyway, I have now worked around that by using a combination of
getaddrinfo + VSA_Malloc.

Best regards,
Sergey

**Comment by graygnuorg** [comment]
Dridi Boukelmoune <notifications@github.com> ha escrit:

> Can you please update your pull request to get rid of the merge commit?

Yes, of course.  I submitted a cleaner request now.

Best regards,
Sergey

**Comment by Dridi** [comment]
> 9 files changed, 66 insertions, 335 deletions

Quite the diff stat!

If you think we should expose `VSS_` functions to VMODs, feel free to start a thread on either misc@ or dev@ mailing lists.

**Pull request closed without merging**
