### PR TITLE
add VMOD unidirectors

### PR DESCRIPTION
**Pull request by ehocdet**
Hi,

Would it be possible to add this vmod on the Varnish Project homepage?
Thanks

### CODE REVIEW

**Comment by nigoroll** [comment]
This is probably not relevant for inclusion in the vmod directory, but can you explain why you need a different interface to what seems to be the more or less the same director code?

**Comment by lkarsten** [comment]
https://github.com/Gandi/libvmod-unidirectors

**Comment by nigoroll** [comment]
@lkarsten thanks, I read it. So is the key thing the ability to change the director type? Why would I want to do this rather than having two directors of different type to the same set of backends? I'd just like to understand what the use case is.

**Comment by lkarsten** [comment]
@nigoroll +1.

**Comment by ehocdet** [comment]
@nigoroll of course
On start we used a varnish3 based implementation.
We generate C-inline to map vhost to director in O(1)   (in summary).
Time spent in vcl.load is also a relevant thing.

vmod_directors introduce in varnish4 break our usage.
. one type per director is painful for C-inline map
. lack of vdi_resolve_f  on hash director break varnish3 compatibility (usage and stack directors)
The need to integrate custom function in vmod, like search (allow backends to self purge without the need of acl).
I implemented this vmod to unify directors and add vcl interface to custom function.

What differs from vmod_directors:
. One director to manipulate weighted backend uniformly.
. director with hash can be stack as in varnish3
. load-balancing method can be changed dynamically
also:
. least-connection implementation (need https://github.com/varnishcache/varnish-cache/pull/1922)
. round-robin is weighted (and use wrlock)
. vd->vbm mechanism, is set in temporary workspace, not lock needed.

**Comment by nigoroll** [comment]
@ehocdet thanks - this touches many points which I hope we'll get back to in varnish core eventually.
@lkarsten ok to merge?

**Comment by huayra** [comment]
So this merge is to add this to the directory, not a proposal to add this to the Varnish core, right?

If so, it might be fine to merge so people can find it here and choose whether they want to use it or not.

**Comment by nigoroll** [comment]
@huayra fine for me, I was waiting for @lkarsten to OK because he had asked me not to merge on IRC

**Comment by nigoroll** [comment]
merged with 1770a2cde0a2dbe6f0b03fe2ced0bb1d3fd1facf

**Comment by nigoroll** [comment]
FTR quote @bsdphk on irc "Ohh, it can surely go on the list, no censorship or filtering there."

**Pull request closed without merging**
