### PR TITLE
vmod cleaning

### PR DESCRIPTION
**Pull request by gquintard**
two commits in this PR:
- regrouping [varnish-modules](https://github.com/varnish/varnish-modules) under one entry
- delete ancient entries. I basically removed all the lines advertising only `3.0` support with no commit to the code for 4-5 years

In my opinion we should also remove entries not supporting at least `6.0-lts`, but that can come later

### CODE REVIEW

**Comment by nigoroll** [comment]
I lean towards 👎🏽 
* old vmods may still be useful for resurrection
* for the varnish-modules bundle, I think it is helpful to have the individual vmods in the list

That said, I think we could move abandonware-candidates to a separate section

**Comment by bsdphk** [comment]
+1 on getting the abandonware firmly segregated

+¼ on removing it entirely.

**Comment by nigoroll** [comment]
pow wow:
* VS to decide on varnish-modules
* Consensus to add an "archived vmods" section

**Comment by gquintard** [comment]
closing in favor of #109

**Pull request closed without merging**
